/**
 * npm run db:setup-sql: builds the one block of SQL pasted into Supabase's SQL editor.
 * It creates the tables (from drizzle/*.sql), locks them with row-level security,
 * and installs the hundred_exec function. Safe to run again.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs"
import path from "node:path"

const root = process.cwd()
const migrations = readdirSync(path.join(root, "drizzle"))
  .filter((f) => f.endsWith(".sql"))
  .sort()
  .flatMap((f) => readFileSync(path.join(root, "drizzle", f), "utf8").split("--> statement-breakpoint"))
  .map((s) => s.trim())
  .filter(Boolean)

// One line per statement, so nothing can be split in the middle by the SQL editor.
const oneLine = (stmt: string) => stmt.replace(/\s+/g, " ").replace(/\( /g, "(").replace(/ \)/g, ")").trim().replace(/;$/, "")
const wrap = (stmt: string) =>
  `do $do$ begin ${oneLine(stmt)}; exception when duplicate_table or duplicate_object or duplicate_column then null; end $do$;`

const tables = [...new Set(migrations.flatMap((s) => [...s.matchAll(/CREATE TABLE "([^"]+)"/g)].map((m) => m[1])))]

const sql = [
  "-- Hundred: database setup. Paste into Supabase → SQL Editor → Run. Safe to run again.",
  "",
  ...migrations.map(wrap),
  "",
  "-- Nothing is readable with the public key: only the server's service key gets in.",
  ...tables.map((t) => `alter table public."${t}" enable row level security;`),
  "",
  readFileSync(path.join(root, "supabase/exec.sql"), "utf8").trim(),
  "",
].join("\n")

writeFileSync(path.join(root, "supabase/setup.sql"), sql)
writeFileSync(path.join(root, "src/db/setup-sql.ts"), `// Generated by scripts/setup-sql.ts. Do not edit.\nexport const SETUP_SQL = ${JSON.stringify(sql)}\n`)
console.log(`Wrote supabase/setup.sql (${sql.length} characters, ${tables.length} tables)`)
